language: java
sudo: false

addons:
  artifacts:
    paths:
      - build/reports/allTests
    target_paths: Travis/$TRAVIS_BUILD_NUMBER/$TRAVIS_JOB_NUMBER

env:
  global:
    - LD_LIBRARY_PATH=${TRAVIS_BUILD_DIR}/travis/lib/ubuntu-12.04.5-amd64
    - BUILD_IDV=false

matrix:
  include:
    - jdk: oraclejdk7
    - jdk: oraclejdk8
    - jdk: openjdk7
#      env: BUILD_IDV=true

script:
  # If we need to do an IDV build, run the script
  - if [[ $BUILD_IDV == true ]]; then
      travis/build_idv.sh;
    fi

  - if [[ $BUILD_IDV == false ]]; then
      echo If available, test report at;
      echo http://unidata-tds-tests.s3.amazonaws.com/Travis/${TRAVIS_BUILD_NUMBER}/${TRAVIS_JOB_NUMBER}/index.html;
      ./gradlew --info testAll;
    fi

cache:
  directories:
    - $HOME/.gradle
